apiVersion: v1
kind: Service
metadata:
  name: httpd-nodeport-svc
spec:
  selector:
    app: default-httpd
  type: NodePort
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
      nodePort: 30001
